meta_product_name: "mixmyBand"
meta_title: "For every music lover - mixmyBand [discover.share.love]:: live music"
meta_description: "mixmyBand is an app for every music lover, helping an Artist to mix his music with an Eventer's venue that fits his style & vice-versa!"
meta_image: "mixmyband-cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
